name: Build and Execute Name Sorter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore NameSorterSolution.sln

      - name: Build
        run: dotnet build NameSorterSolution.sln --no-restore --configuration Release

      - name: Run NameSorter
        working-directory: NameSorter
        run: dotnet run --project NameSorter.csproj --configuration Release ./unsorted-names-list.txt

      - name: Run Tests
        run: dotnet test NameSorter.Tests/NameSorter.Tests.csproj --no-build --configuration Release --verbosity normal

      - name: Calculate test metrics
        run: |
          TEST_RESULT=$(dotnet test NameSorter.Tests/NameSorter.Tests.csproj --no-build --configuration Release --verbosity normal | grep -oP 'Total tests: \K\d+')
          PASSED_TESTS=$(dotnet test NameSorter.Tests/NameSorter.Tests.csproj --no-build --configuration Release --verbosity normal | grep -oP 'Passed: \K\d+')
          echo "Total Tests: $TEST_RESULT"
          echo "Passed Tests: $PASSED_TESTS"
          echo "Percentage of Tests Passed: $(($PASSED_TESTS * 100 / $TEST_RESULT))%"

      - name: Commit sorted-names-list.txt
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add NameSorter/sorted-names-list.txt
          git commit -m "Add sorted-names-list.txt from CI run" || echo "No changes to commit"
          git push
